### ISSUE TITLE
Navbar Text Alignment 

### ISSUE THREAD

**Issue by Harshil-Jani** [BhagyaRana/WP_Website#25]
![image](https://user-images.githubusercontent.com/79367883/127098182-256bd861-f1f5-46f4-a95f-b9599a5a0e4a.png)
The Text within the Navbar is not aligned. In CSS file(phone.css) unwanted padding property causes the issue.
`#navbar ul li a {`
  `  font-size: 1rem;`
 `   padding: 0px 7px;`
   ` padding-bottom: 8px;`
`}`

Removing  `padding-bottom:8px;` and changing `padding : 5px 7px;` will fix the issue.

**Comment by bhagyarana** [comment]
**Thanks** for Mentioning this Issue in UI!  
It has been Fixed as Suggested!
